## Rubric

Instructions: DELETE this cell before you submit via a `git push` to your repo before deadline. This cell is for your reference only and is not needed in your report. 

Scoring: Out of 10 points

- Each Developing  => -2 pts
- Each Unsatisfactory/Missing => -4 pts
  - until the score is 

If students address the detailed feedback in a future checkpoint they will earn these points back


|                  | Unsatisfactory                                                                                                                                                                                                    | Developing                                                                                                                                                                                              | Proficient                                     | Excellent                                                                                                                              |
|------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------|
| Data relevance   | Did not have data relevant to their question. Or the datasets don't work together because there is no way to line them up against each other. If there are multiple datasets, most of them have this trouble | Data was only tangentially relevant to the question or a bad proxy for the question. If there are multiple datasets, some of them may be irrelevant or can't be easily combined.                       | All data sources are relevant to the question. | Multiple data sources for each aspect of the project. It's clear how the data supports the needs of the project.                         |
| Data description | Dataset or its cleaning procedures are not described. If there are multiple datasets, most have this trouble                                                                                              | Data was not fully described. If there are multiple datasets, some of them are not fully described                                                                                                      | Data was fully described                       | The details of the data descriptions and perhaps some very basic EDA also make it clear how the data supports the needs of the project. |
| Data wrangling   | Did not obtain data. They did not clean/tidy the data they obtained.  If there are multiple datasets, most have this trouble                                                                                 | Data was partially cleaned or tidied. Perhaps you struggled to verify that the data was clean because they did not present it well. If there are multiple datasets, some have this trouble | The data is cleaned and tidied.                | The data is spotless and they used tools to visualize the data cleanliness and you were convinced at first glance                      |

# COGS 108 - Data Checkpoint

## Authors

Instructions: REPLACE the contents of this cell with your team list and their contributions. Note that this will change over the course of the checkpoints

This is a modified [CRediT taxonomy of contributions](https://credit.niso.org). For each group member please list how they contributed to this project using these terms:
> Analysis, Background research, Conceptualization, Data curation, Experimental investigation, Methodology, Project administration, Software, Visualization, Writing – original draft, Writing – review & editing

Example team list and credits:
- Alice Anderson: Conceptualization, Data curation, Methodology, Writing - original draft
- Bob Barker:  Analysis, Software, Visualization
- Charlie Chang: Project administration, Software, Writing - review & editing
- Dani Delgado: Analysis, Background research, Visualization, Writing - original draft

## Research Question

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Background and Prior Work

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Hypothesis

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Data

### Data overview

For each dataset include the following information
- Dataset #1
  - Dataset Name: Video Game Sales Dataset (Kaggle)

  - Link to the dataset: https://www.kaggle.com/datasets/anandshaw2001/video-game-sales

  - Number of observations: Approximately 16,000 video game entries.

  - Number of variables: 11 variables in total. However, for this project we focus on a subset of 5 variables (4      predictors + 1 outcome).

  - Description of the variables most relevant to this project：
    Each row represents a single video game release (often platform-specific).
    We focus on the following variables:
    Platform – The console or platform where the game was released (e.g., PS4, Xbox, PC).
    Genre – The primary genre classification of the game.
    Publisher – The publishing company responsible for distribution.
    Year – The release year of the game.
    Global_Sales – Total worldwide sales measured in millions of units sold.
    Global_Sales is measured in millions of copies sold.
    For this project: Platform, Genre, Publisher, and Year are used as pre-release predictors.
    Global_Sales is used to construct a year-normalized bestseller indicator.
    
  - Descriptions of any shortcomings this dataset has with repsect to the project：
    1. Sales figures are scraped and may contain measurement error.
    2. The dataset does not include marketing intensity, franchise indicators, or pre-order information.
    3. Multiple platform versions of the same game appear as separate observations.
    Some missing values exist in the Year and Publisher columns.
    Despite these limitations, the dataset contains sufficient structured metadata to support our predictive
    modeling framework.

In [1]:
# Run this code every time when you're actively developing modules in .py files.  It's not needed if you aren't making modules
#
## this code is necessary for making sure that any modules we load are updated here 
## when their source code .py files are modified

%load_ext autoreload
%autoreload 2

In [2]:
# Setup code -- this only needs to be run once after cloning the repo!
# this code downloads the data from its source to the `data/00-raw/` directory
# if the data hasn't updated you don't need to do this again!

# if you don't already have these packages (you should!) uncomment this line
# %pip install requests tqdm

import sys
sys.path.append('./modules') # this tells python where to look for modules to import

import get_data # this is where we get the function we need to download data

# replace the urls and filenames in this list with your actual datafiles
# yes you can use Google drive share links or whatever
# format is a list of dictionaries; 
# each dict has keys of 
#   'url' where the resource is located
#   'filename' for the local filename where it will be stored 
datafiles = [
    { 'url': 'https://raw.githubusercontent.com/fivethirtyeight/data/refs/heads/master/airline-safety/airline-safety.csv', 'filename':'airline-safety.csv'},
    { 'url': 'https://raw.githubusercontent.com/fivethirtyeight/data/refs/heads/master/bad-drivers/bad-drivers.csv', 'filename':'bad-drivers.csv'}
]

get_data.get_raw(datafiles,destination_directory='data/00-raw/')

Overall Download Progress:   0%|          | 0/2 [00:00<?, ?it/s]
Downloading airline-safety.csv:   0%|          | 0.00/1.23k [00:00<?, ?B/s]
Overall Download Progress:  50%|█████     | 1/2 [00:00<00:00,  5.84it/s]

Successfully downloaded: airline-safety.csv

Downloading bad-drivers.csv:   0%|          | 0.00/1.37k [00:00<?, ?B/s]
Overall Download Progress: 100%|██████████| 2/2 [00:00<00:00,  6.17it/s]

Successfully downloaded: bad-drivers.csv

### Dataset #1 

Instructions: 
1. Change the header from Dataset #1 to something more descriptive of the dataset
2. Write a few paragraphs about this dataset. Make sure to cover
   1. Describe the important metrics, what units they are in, and giv some sense of what they mean.  For example "Fasting blood glucose in units of mg glucose per deciliter of blood.  Normal values for healthy individuals range from 70 to 100 mg/dL.  Values 100-125 are prediabetic and values >125mg/dL indicate diabetes. Values <70 indicate hypoglycemia. Fasting idicates the patient hasn't eaten in the last 8 hours.  If blood glucose is >250 or <50 at any time (regardless of the time of last meal) the patient's life may be in immediate danger"
   2. If there are any major concerns with the dataset, describe them. For example "Dataset is composed of people who are serious enough about eating healthy that they voluntarily downloaded an app dedicated to tracking their eating patterns. This sample is likely biased because of that self-selection. These people own smartphones and may be healthier and may have more disposable income than the average person.  Those who voluntarily log conscientiously and for long amounts of time are also likely even more interested in health than those who download the app and only log a bit before getting tired of it"
3. Use the cell below to 
    1. load the dataset 
    2. make the dataset tidy or demonstrate that it was already tidy
    3. demonstrate the size of the dataset
    4. find out how much data is missing, where its missing, and if its missing at random or seems to have any systematic relationships in its missingness
    5. find and flag any outliers or suspicious entries
    6. clean the data or demonstrate that it was already clean.  You may choose how to deal with missingness (dropna of fillna... how='any' or 'all') and you should justify your choice in some way
    7. You will load raw data from `data/00-raw/`, you will (optionally) write intermediate stages of your work to `data/01-interim` and you will write the final fully wrangled version of your data to `data/02-processed`
4. Optionally you can also show some summary statistics for variables that you think are important to the project
5. Feel free to add more cells here if that's helpful for you

In [3]:
## YOUR CODE TO LOAD/CLEAN/TIDY/WRANGLE THE DATA GOES HERE
import pandas as pd
import numpy as np
import os

df_raw = pd.read_csv('data/00-raw/vgsales.csv')

df_raw.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

In [4]:
# Quick Check
print("Shape:", df_raw.shape)
print("Columns:", df_raw.columns.tolist())

Shape: (16598, 11)
Columns: ['Rank', 'Name', 'Platform', 'Year', 'Genre', 'Publisher', 'NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales']

In [5]:
# Missing Value Check

# missing counts of every columns
missing_counts = df_raw.isna().sum()

# missng percentage of every column
missing_percent = (df_raw.isna().mean() * 100).round(2)

# make a form of the above missing information
missing_df = pd.DataFrame({
    "Missing_Count": missing_counts,
    "Missing_Percent (%)": missing_percent
}).sort_values(by="Missing_Count", ascending=False)

print(missing_df)

# Check complete missing row
fully_missing_rows = df_raw.isna().all(axis=1).sum()
print(f"Completely empty rows: {fully_missing_rows}")

              Missing_Count  Missing_Percent (%)
Year                    271                 1.63
Publisher                58                 0.35
Rank                      0                 0.00
Name                      0                 0.00
Platform                  0                 0.00
Genre                     0                 0.00
NA_Sales                  0                 0.00
EU_Sales                  0                 0.00
JP_Sales                  0                 0.00
Other_Sales               0                 0.00
Global_Sales              0                 0.00
Completely empty rows: 0

In [6]:
# Cleaning Missing Values

print("Before cleaning:", df_raw.shape)

df_clean = df_raw.dropna(subset=["Year", "Publisher"])

print("After cleaning:", df_clean.shape)

# Confirm the result is good
print("\nRemaining missing values:")
print(df_clean.isna().sum())

Before cleaning: (16598, 11)
After cleaning: (16291, 11)

Remaining missing values:
Rank            0
Name            0
Platform        0
Year            0
Genre           0
Publisher       0
NA_Sales        0
EU_Sales        0
JP_Sales        0
Other_Sales     0
Global_Sales    0
dtype: int64

In [7]:
# Select Relevant Variables

selected_columns = [
    "Year",
    "Platform",
    "Genre",
    "Publisher",
    "Global_Sales"
]

df_model = df_clean[selected_columns].copy()

print("Model dataset shape:", df_model.shape)
df_model.head()

Model dataset shape: (16291, 5)

     Year Platform         Genre Publisher  Global_Sales
0  2006.0      Wii        Sports  Nintendo         82.74
1  1985.0      NES      Platform  Nintendo         40.24
2  2008.0      Wii        Racing  Nintendo         35.82
3  2009.0      Wii        Sports  Nintendo         33.00
4  1996.0       GB  Role-Playing  Nintendo         31.37

In [8]:
# Year-normalized percentile

df_model["Sales_Percentile"] = (
    df_model
    .groupby("Year")["Global_Sales"]
    .rank(pct=True)
)

df_model.head()

     Year Platform         Genre Publisher  Global_Sales  Sales_Percentile
0  2006.0      Wii        Sports  Nintendo         82.74               1.0
1  1985.0      NES      Platform  Nintendo         40.24               1.0
2  2008.0      Wii        Racing  Nintendo         35.82               1.0
3  2009.0      Wii        Sports  Nintendo         33.00               1.0
4  1996.0       GB  Role-Playing  Nintendo         31.37               1.0

In [9]:
# Create Bestseller Levels

def classify_bestseller(p):
    if p >= 0.90:
        return "Top 10%"
    elif p >= 0.75:
        return "75–90%"
    elif p >= 0.25:
        return "25–75%"
    else:
        return "Bottom 25%"

df_model["Bestseller_Level"] = df_model["Sales_Percentile"].apply(classify_bestseller)

df_model.head()

,Year,Platform,Genre,Publisher,Global_Sales,Sales_Percentile,Bestseller_Level
0,2006.0,Wii,Sports,Nintendo,82.74,1.0,Top 10%
1,1985.0,NES,Platform,Nintendo,40.24,1.0,Top 10%
2,2008.0,Wii,Racing,Nintendo,35.82,1.0,Top 10%
3,2009.0,Wii,Sports,Nintendo,33.00,1.0,Top 10%
4,1996.0,GB,Role-Playing,Nintendo,31.37,1.0,Top 10%

In [10]:
# Outlier Check for Global_Sales

print("Basic statistics for Global_Sales:")
print(df_model["Global_Sales"].describe())

print("\nTop 10 highest selling games:")
print(df_model.sort_values("Global_Sales", ascending=False).head(10))

print("\nBottom 10 lowest selling games:")
print(df_model.sort_values("Global_Sales", ascending=True).head(10))

Basic statistics for Global_Sales:
count    16291.000000
mean         0.540910
std          1.567345
min          0.010000
25%          0.060000
50%          0.170000
75%          0.480000
max         82.740000
Name: Global_Sales, dtype: float64

Top 10 highest selling games:
     Year Platform         Genre Publisher  Global_Sales  Sales_Percentile  \
0  2006.0      Wii        Sports  Nintendo         82.74          1.000000
1  1985.0      NES      Platform  Nintendo         40.24          1.000000
2  2008.0      Wii        Racing  Nintendo         35.82          1.000000
3  2009.0      Wii        Sports  Nintendo         33.00          1.000000
4  1996.0       GB  Role-Playing  Nintendo         31.37          1.000000
5  1989.0       GB        Puzzle  Nintendo         30.26          1.000000
6  2006.0       DS      Platform  Nintendo         30.01          0.999008
7  2006.0      Wii          Misc  Nintendo         29.02          0.998016
8  2009.0      Wii      Platform  Nintendo         28.62          0.999301
9  1984.0      NES       Shooter  Nintendo         28.31          1.000000

  Bestseller_Level
0          Top 10%
1          Top 10%
2          Top 10%
3          Top 10%
4          Top 10%
5          Top 10%
6          Top 10%
7          Top 10%
8          Top 10%
9          Top 10%

Bottom 10 lowest selling games:
         Year Platform       Genre                    Publisher  Global_Sales  \
16597  2003.0      GBA    Platform                      Wanadoo          0.01
16185  2009.0      PSP   Adventure             Arc System Works          0.01
16184  2007.0      PS2    Fighting                 SNK Playmore          0.01
16183  2013.0      PSP   Adventure               Kadokawa Games          0.01
16182  2013.0      PSP        Misc                 Idea Factory          0.01
16181  2011.0      PS3     Shooter  Sony Computer Entertainment          0.01
16180  2007.0      PS2    Fighting                        Taito          0.01
16186  2009.0       PC    Strategy              Electronic Arts          0.01
16179  2006.0      PS3      Sports                         Sega          0.01
16177  2007.0       PC  Simulation              Electronic Arts          0.01

       Sales_Percentile Bestseller_Level
16597          0.012258       Bottom 25%
16185          0.024808       Bottom 25%
16184          0.027893       Bottom 25%
16183          0.026557       Bottom 25%
16182          0.026557       Bottom 25%
16181          0.016285       Bottom 25%
16180          0.027893       Bottom 25%
16186          0.024808       Bottom 25%
16179          0.023313       Bottom 25%
16177          0.027893       Bottom 25%

In [11]:
# Save Processed Dataset

os.makedirs("data/02-processed", exist_ok=True)
df_model.to_csv("data/02-processed/video_game_model_data.csv", index=False)

Outlier Assessment：
The distribution of Global_Sales is highly right-skewed, with a small number of extremely high-selling games (e.g., Wii Sports). However, these values reflect genuine market phenomena rather than data errors. Since our outcome variable is based on within-year percentile ranking rather than absolute sales, extreme values do not distort the modeling framework. Therefore, no trimming or transformation was applied.

## Ethics

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Team Expectations

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Project Timeline Proposal

Instructions: Replace this with your timeline.  **PLEASE UPDATE your Timeline!** No battle plan survives contact with the enemy, so make sure we understand how your plans have changed.  Also if you have lost points on the previous checkpoint fix them